name: 刷步数

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 5 16,23 * * *
  watch:
    types: started

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Get server time
        run: echo "Server time： $(TZ=Asia/Shanghai date)"
      - name: Generate random number
        id: Random steps
        run: |
          hour=$(TZ=Asia/Shanghai date +%H)
          if [[ $hour -ge 7 && $hour -lt 16 ]]; then
            echo "Generating random number for the second time"
            lower_limit=23607
            upper_limit=27141
            step=$(( $RANDOM % (35000 - 30000 + 1) + 30000 ))
          else
            echo "Generating random number for the first time"
            lower_limit=19888
            upper_limit=23422
            step=$(( $RANDOM % (20000 - 15000 + 1) + 15000 ))
          fi
          step="$(( RANDOM % (upper_limit - lower_limit + 1) + lower_limit ))"
          echo "Random number: ${step}"
          user="${{ secrets.USER }}"
          pwd="${{ secrets.PWD }}"
          curl "https://sport-api.yyink.cn/api/mi?user=${user}&password=${pwd}&step=${step}"


 #build:
 #  runs-on: ubuntu-latest
 #  steps:
 #    - uses: actions/checkout@v2
 #    - name: 初始化Python
 #      uses: actions/setup-python@v2
 #      with:
 #        python-version: 3.7
 #    - name: 开始
 #      run: |
 #        pip install requests
 #        pmode='${{ secrets.PMODE }}'
 #        pkey='${{ secrets.PKEY }}'
 #        user='${{ secrets.USER }}'
 #        pwd='${{ secrets.PWD }}'
 #        step='${{ secrets.STEP }}'
 #        
 #        
 #         https://sport-api.yyink.cn/api/mi?user=18720158315&password=caixin9749&step=22002
 #        python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}  


